routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Support\Facades\Input;
//use League\Glide\Responses\LaravelResponseFactory;
//use League\Glide\ServerFactory;

Route::get('/', 'FrontPageController@homepage');
Route::get('/about', 'FrontPageController@aboutUs');
Route::get('/events', 'FrontPageController@events');
Route::get('/event/{id}', 'FrontPageController@event_detail')->name('frontend.event_detail');

Route::get('/registration', 'FrontPageController@registration');
Route::post('/registration', 'RegistrationController@store');

Auth::routes();

Route::get('/home', 'HomeController@index');

//
//Route::get('glide/{path}', function ($path) {
//	$server = ServerFactory::create([
//		'source'   => app('filesystem')->disk('public_images')->getDriver(),
//		'cache'    => storage_path('glide'),
//		'response' => new LaravelResponseFactory()
//	]);
//
//	return $server->getImageResponse($path, Input::query());
//})->where('path', '.+');

Auth::routes();

Route::get('/home', 'HomeController@index');


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin'], 'as' => 'admin.'], function () {
	Route::resource('collaborations', 'CollaborationController');
	Route::resource('venues', 'VenueController');
	Route::resource('events', 'EventController');
	Route::resource('events/{event}/pictures', 'PictureController');
	Route::get('events/{event}/registered_users', ['as' => 'events.registered_users', 'uses' => 'EventController@registeredUsers']);
	Route::get('events/{event}/meeting/{users}/', ['as' => 'events.arrange_meeting', 'uses' => 'EventController@arrange_meeting']);
	Route::post('events/{event}/meeting/{users}/', ['as' => 'events.arrange_meeting.store', 'uses' => 'EventController@arrange_meetingPost']);
	Route::resource('jobPositions', 'JobPositionController');
	Route::resource('businessSectors', 'BusinessSectorController');
	Route::resource('attendees', 'AttendeeController');
});

Route::group(['prefix' => 'attendee', 'middleware' => ['auth', 'role:attendee'], 'as' => 'attendee.'], function () {
	Route::get('events_for_attendees', ['as' => 'events_for_attendees', 'uses' => 'EventsForAttendeesController@events_list']);
	Route::get('events_for_attendees/register/{event_id}', ['as' => 'events_for_attendees.register', 'uses' => 'EventsForAttendeesController@registerForEvent']);
	Route::post('events_for_attendees/registerInterest/{event_id}', ['as' => 'events_for_attendees.registerInterest', 'uses' => 'EventsForAttendeesController@registerEventInterest']);
	Route::get('events_for_attendees/register_events', ['as' => 'events_for_attendees.registered_events', 'uses' => 'EventsForAttendeesController@registeredEvents']);
});

//Route::get('admin/collaborations', ['as' => 'admin.collaborations.index', 'uses' => 'CollaborationController@index']);
//Route::post('admin/collaborations', ['as' => 'admin.collaborations.store', 'uses' => 'CollaborationController@store']);
//Route::get('admin/collaborations/create', ['as' => 'admin.collaborations.create', 'uses' => 'CollaborationController@create']);
//Route::put('admin/collaborations/{collaborations}', ['as' => 'admin.collaborations.update', 'uses' => 'CollaborationController@update']);
//Route::patch('admin/collaborations/{collaborations}', ['as' => 'admin.collaborations.update', 'uses' => 'CollaborationController@update']);
//Route::delete('admin/collaborations/{collaborations}', ['as' => 'admin.collaborations.destroy', 'uses' => 'CollaborationController@destroy']);
//Route::get('admin/collaborations/{collaborations}', ['as' => 'admin.collaborations.show', 'uses' => 'CollaborationController@show']);
//Route::get('admin/collaborations/{collaborations}/edit', ['as' => 'admin.collaborations.edit', 'uses' => 'CollaborationController@edit']);
//
//
//Route::get('admin/venues', ['as' => 'admin.venues.index', 'uses' => 'VenueController@index']);
//Route::post('admin/venues', ['as' => 'admin.venues.store', 'uses' => 'VenueController@store']);
//Route::get('admin/venues/create', ['as' => 'admin.venues.create', 'uses' => 'VenueController@create']);
//Route::put('admin/venues/{venues}', ['as' => 'admin.venues.update', 'uses' => 'VenueController@update']);
//Route::patch('admin/venues/{venues}', ['as' => 'admin.venues.update', 'uses' => 'VenueController@update']);
//Route::delete('admin/venues/{venues}', ['as' => 'admin.venues.destroy', 'uses' => 'VenueController@destroy']);
//Route::get('admin/venues/{venues}', ['as' => 'admin.venues.show', 'uses' => 'VenueController@show']);
//Route::get('admin/venues/{venues}/edit', ['as' => 'admin.venues.edit', 'uses' => 'VenueController@edit']);
//
//
//Route::get('admin/events', ['as' => 'admin.events.index', 'uses' => 'EventController@index']);
//Route::post('admin/events', ['as' => 'admin.events.store', 'uses' => 'EventController@store']);
//Route::get('admin/events/create', ['as' => 'admin.events.create', 'uses' => 'EventController@create']);
//Route::put('admin/events/{events}', ['as' => 'admin.events.update', 'uses' => 'EventController@update']);
//Route::patch('admin/events/{events}', ['as' => 'admin.events.update', 'uses' => 'EventController@update']);
//Route::delete('admin/events/{events}', ['as' => 'admin.events.destroy', 'uses' => 'EventController@destroy']);
//Route::get('admin/events/{events}', ['as' => 'admin.events.show', 'uses' => 'EventController@show']);
//Route::get('admin/events/{events}/edit', ['as' => 'admin.events.edit', 'uses' => 'EventController@edit']);
//
//
//Route::get('admin/jobPositions', ['as' => 'admin.jobPositions.index', 'uses' => 'JobPositionController@index']);
//Route::post('admin/jobPositions', ['as' => 'admin.jobPositions.store', 'uses' => 'JobPositionController@store']);
//Route::get('admin/jobPositions/create', ['as' => 'admin.jobPositions.create', 'uses' => 'JobPositionController@create']);
//Route::put('admin/jobPositions/{jobPositions}', ['as' => 'admin.jobPositions.update', 'uses' => 'JobPositionController@update']);
//Route::patch('admin/jobPositions/{jobPositions}', ['as' => 'admin.jobPositions.update', 'uses' => 'JobPositionController@update']);
//Route::delete('admin/jobPositions/{jobPositions}', ['as' => 'admin.jobPositions.destroy', 'uses' => 'JobPositionController@destroy']);
//Route::get('admin/jobPositions/{jobPositions}', ['as' => 'admin.jobPositions.show', 'uses' => 'JobPositionController@show']);
//Route::get('admin/jobPositions/{jobPositions}/edit', ['as' => 'admin.jobPositions.edit', 'uses' => 'JobPositionController@edit']);
//
//
//Route::get('admin/businessSectors', ['as' => 'admin.businessSectors.index', 'uses' => 'BusinessSectorController@index']);
//Route::post('admin/businessSectors', ['as' => 'admin.businessSectors.store', 'uses' => 'BusinessSectorController@store']);
//Route::get('admin/businessSectors/create', ['as' => 'admin.businessSectors.create', 'uses' => 'BusinessSectorController@create']);
//Route::put('admin/businessSectors/{businessSectors}', ['as' => 'admin.businessSectors.update', 'uses' => 'BusinessSectorController@update']);
//Route::patch('admin/businessSectors/{businessSectors}', ['as' => 'admin.businessSectors.update', 'uses' => 'BusinessSectorController@update']);
//Route::delete('admin/businessSectors/{businessSectors}', ['as' => 'admin.businessSectors.destroy', 'uses' => 'BusinessSectorController@destroy']);
//Route::get('admin/businessSectors/{businessSectors}', ['as' => 'admin.businessSectors.show', 'uses' => 'BusinessSectorController@show']);
//Route::get('admin/businessSectors/{businessSectors}/edit', ['as' => 'admin.businessSectors.edit', 'uses' => 'BusinessSectorController@edit']);
//
//
//Route::get('admin/attendees', ['as' => 'admin.attendees.index', 'uses' => 'AttendeeController@index']);
//Route::post('admin/attendees', ['as' => 'admin.attendees.store', 'uses' => 'AttendeeController@store']);
//Route::get('admin/attendees/create', ['as' => 'admin.attendees.create', 'uses' => 'AttendeeController@create']);
//Route::put('admin/attendees/{attendees}', ['as' => 'admin.attendees.update', 'uses' => 'AttendeeController@update']);
//Route::patch('admin/attendees/{attendees}', ['as' => 'admin.attendees.update', 'uses' => 'AttendeeController@update']);
//Route::delete('admin/attendees/{attendees}', ['as' => 'admin.attendees.destroy', 'uses' => 'AttendeeController@destroy']);
//Route::get('admin/attendees/{attendees}', ['as' => 'admin.attendees.show', 'uses' => 'AttendeeController@show']);
//Route::get('admin/attendees/{attendees}/edit', ['as' => 'admin.attendees.edit', 'uses' => 'AttendeeController@edit']);


//Route::get('admin/pictures', ['as' => 'admin.pictures.index', 'uses' => 'PictureController@index']);
//Route::post('admin/pictures', ['as' => 'admin.pictures.store', 'uses' => 'PictureController@store']);
//Route::get('admin/pictures/create', ['as' => 'admin.pictures.create', 'uses' => 'PictureController@create']);
//Route::put('admin/pictures/{pictures}', ['as' => 'admin.pictures.update', 'uses' => 'PictureController@update']);
//Route::patch('admin/pictures/{pictures}', ['as' => 'admin.pictures.update', 'uses' => 'PictureController@update']);
//Route::delete('admin/pictures/{pictures}', ['as' => 'admin.pictures.destroy', 'uses' => 'PictureController@destroy']);
//Route::get('admin/pictures/{pictures}', ['as' => 'admin.pictures.show', 'uses' => 'PictureController@show']);
//Route::get('admin/pictures/{pictures}/edit', ['as' => 'admin.pictures.edit', 'uses' => 'PictureController@edit']);


Route::get('admin/meetings', ['as'=> 'admin.meetings.index', 'uses' => 'MeetingController@index']);
Route::post('admin/meetings', ['as'=> 'admin.meetings.store', 'uses' => 'MeetingController@store']);

resources/views/frontend/about.blade.php
@extends('layouts.frontend')
@section('content')
    <section class="aboutUsHeader">
        <div class="inner_shadow">
            <h2>
                <span>Company Profile</span>
            </h2>
            <p>Some text about company profile</p>
        </div>
    </section>

    <section class="company_profile">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div>

                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                                      data-toggle="tab">Who are we?</a></li>
                            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                                       data-toggle="tab">Why choose us?</a></li>
                            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                                       data-toggle="tab">How to?</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="home">
                                <hr class="invisible">
                                <div class="row">
                                    <div class="col-sm-6 text-justify">
                                        <h3>Lorem ipsum dolor sit amet, consect adipiing elit </h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                    </div>
                                    <div class="col-sm-6">
                                        <img src="{{ url('/images/frontend/profile.jpg') }}" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="profile">
                                <hr class="invisible">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <img src="{{ url('/images/frontend/profile.jpg') }}" class="img-responsive" alt="">
                                    </div>
                                    <div class="col-sm-6 text-justify">
                                        <h3>Lorem ipsum dolor sit amet, consect adipiing elit </h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                    </div>

                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="messages">
                                <hr class="invisible">
                                <div class="row">
                                    <div class="col-sm-6 text-justify">
                                        <h3>Lorem ipsum dolor sit amet, consect adipiing elit </h3>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fuga fugiat
                                            itaque nemo odio optio quasi tempora. Architecto aut consectetur delectus
                                            distinctio earum incidunt iure magnam nam quod similique. Placeat.
                                        </p>
                                    </div>
                                    <div class="col-sm-6">
                                        <img src="{{ url('/images/frontend/profile.jpg') }}" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    {{--    @include('frontend._partials.events')--}}
    @include('frontend._includes.subscribeBox')
@endsection

resources/views/frontend/event_detail.blade.php
@extends('layouts.frontend')
@section('content')
    <section class="eventsHeader">
        <div class="inner_shadow">
            <h2>
                <span>{{ $event->title }}</span>
            </h2>
        </div>
    </section>

    <section class="events_details">
        <div class="container">
            <div class="row">
                @if($event->image_path)
                    <div class="col-sm-6">
                        <img src="{{ url($event->image_path) }}" class="img-responsive img-thumbnail" alt="">
                    </div>
                @endif
                <div class="col-sm-6 event-detail--info">
                    <h4>{{ $event->title }} -
                        @if($signedIn && $currentUser->hasRole('attendee'))
                            @if($currentUser->attendee->registered_events->contains($event->id))
                                <a class='btn btn-success disabled btn-xs'>
                                    <i class="fa fa-check"></i> Registered
                                </a>
                            @else
                                <a href="{!! route('attendee.events_for_attendees.register', [$event->id]) !!}"
                                   class='btn btn-success btn-xs'><i
                                        class="fa fa-check"></i> Register</a>
                            @endif
                        @endif
                    </h4>
                    <hr>
                    @if($signedIn && $currentUser->hasRole('attendee') && $currentUser->attendee->registered_events->contains($event->id))
                        <form style="background: rgba(0,0,0,0.3); padding: 20px 0; border-radius: 5px;"
                              action="{{ route('attendee.events_for_attendees.registerInterest',[$event->id]) }}"
                              method="post">
                        {{ csrf_field() }}
                        <!--- Company Field --->
                            <div class="form-group company-field col-sm-6" id="company-field">
                                {!! Form::label('company', 'Company / Institute:') !!}
                                {!! Form::text('company', $eventInterestInfo['company'], ['class' => 'form-control']) !!}
                                {!! $errors->first('company', '<p class="help-block error-msg">:message</p>') !!}
                            </div>

                            <!--- Name Field --->
                            <div class="form-group name-field col-sm-6" id="name-field">
                                {!! Form::label('name', 'Name:') !!}
                                {!! Form::text('name', $eventInterestInfo['name'], ['class' => 'form-control']) !!}
                                {!! $errors->first('name', '<p class="help-block error-msg">:message</p>') !!}
                            </div>


                            <!--- WorkingIn Field --->
                            <div class="form-group working_in-field col-sm-12" id="working_in-field">
                                {!! Form::label('working_in', 'Working In:') !!}
                                {!! Form::textarea('working_in', $eventInterestInfo['working_in'], ['class' => 'form-control','rows'=>2]) !!}
                                {!! $errors->first('working_in', '<p class="help-block error-msg">:message</p>') !!}
                            </div>

                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                        <br>
                    @endif
                    <p>Starts : <span class="time_pill">{{ $event->starts_at->toDayDateTimeString() }}</span>, Ends:
                        <span
                            class="time_pill">{{ $event->ends_at->toDayDateTimeString() }}</span></p>
                    <p>Venue: {{ $event->venue->name }}</p>
                    <p>{{ $event->description }}</p>
                </div>
            </div>
        </div>
    </section>

    {{--    @include('frontend._partials.events')--}}
    {{--    @include('frontend._includes.subscribeBox')--}}
@endsection

@push('bottomJS')
@endpush

resources/views/frontend/events.blade.php
@extends('layouts.frontend')
@section('content')
    <section class="eventsHeader">
        <div class="inner_shadow">
            <h2>
                <span>Events</span>
            </h2>
            <p>Overview of all global events</p>

        </div>
    </section>

    <section class="events_details">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        @foreach($events as $event)
                            {{--<div class="grid-item">--}}
                            {{--<div class="event--single">--}}
                            <div class="col-md-4">
                                <div class="card card-product">
                                    <div class="card-image" data-header-animation="true">
                                        <a href="javascript:void(0);">
                                            {{--@if($event->image_path)--}}
                                            {{--<img src="{{ url($event->image_path) }}?w=450" class="img"--}}
                                            {{--alt="">--}}
                                            {{--@endif--}}
                                            <img src="/images/card-3.jpeg" class="img"
                                                 alt="">
                                        </a>
                                    </div>
                                    <div class="card-content">
                                        @role('admin')
                                        <div class="card-actions">
                                            <button type="button"
                                                    class="btn btn-danger btn-simple fix-broken-card">
                                                <i class="material-icons">build</i> Fix Header!
                                            </button>
                                            <button type="button" class="btn btn-default btn-simple"
                                                    rel="tooltip" data-placement="bottom" title="View">
                                                <i class="material-icons">art_track</i>
                                            </button>
                                            <button type="button" class="btn btn-success btn-simple"
                                                    rel="tooltip" data-placement="bottom" title="Edit">
                                                <i class="material-icons">edit</i>
                                            </button>
                                            <button type="button" class="btn btn-danger btn-simple"
                                                    rel="tooltip" data-placement="bottom" title="Remove">
                                                <i class="material-icons">close</i>
                                            </button>
                                        </div>
                                        @endrole
                                        <h4 class="card-title">
                                            <a href="{{ route('frontend.event_detail',[$event->id]) }}">{{ $event->title }}</a>
                                        </h4>
                                        <div class="card-description">
                                            {{ $event->description }}
                                            {{--<div class="stats">--}}
                                            {{--<i class="material-icons">timer</i>--}}
                                            {{--<p>--}}
                                            {{--{{ $event->starts_at->toDayDateTimeString() }}--}}
                                            {{--- {{ $event->ends_at->toDayDateTimeString() }}--}}
                                            {{--</p>--}}
                                            {{--</div>--}}
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="stats" data-toggle="tooltip" data-placement="top"
                                             title="Starts At: {{ $event->starts_at->toDayDateTimeString() }} - Ends At: {{ $event->ends_at->toDayDateTimeString() }}">
                                            <i class="material-icons">timer</i>
                                            {{ $event->starts_at->toDayDateTimeString() }}
                                        </div>
                                        <div class="stats pull-right">
                                            <i class="material-icons">place</i>
                                            {{ $event->venue->name }}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {{--@if($event->image_path)--}}
                            {{--<img src="{{ url($event->image_path) }}?w=450" class="img-responsive"--}}
                            {{--alt="">--}}
                            {{--@endif--}}
                            {{--<div class="event--single-detail">--}}
                            {{--<span--}}
                            {{--class="event--single-date">{{ $event->starts_at->toDayDateTimeString() }}</span>--}}
                            {{--<h4>--}}
                            {{--<a href="{{ route('frontend.event_detail',[$event->id]) }}">{{ $event->title }}</a>--}}
                            {{--</h4>--}}
                            {{--<p>{{ $event->description }}</p>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                            {{--</div>--}}
                        @endforeach
                    </div>
                </div>

                <div class="grid">
                    <!-- .grid-sizer empty element, only used for element sizing -->
                    <div class="grid-sizer"></div>
                    <div class="gutter-sizer"></div>


                </div>
            </div>
        </div>
        </div>
    </section>

    {{--    @include('frontend._partials.events')--}}
    {{--    @include('frontend._includes.subscribeBox')--}}
@endsection

@push('bottomJS')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    //$('.grid').isotope({
    //itemSelector: '.grid-item',
    //percentPosition: true,
    //masonry: {
    //// use outer width of grid-sizer for columnWidth
    //columnWidth: '.grid-sizer',
    //gutter: '.gutter-sizer'
    //}
    //})
</script>
@endpush

resources/views/frontend/home.blade.php
@extends('layouts.frontend')
@section('content')
    <div class="topImage">
        <img src="{{ asset('/images/frontend/header.jpg') }}" class="img-responsive" alt="">
    </div>

    @include('frontend._partials.events')
    @include('frontend._includes.subscribeBox')
@endsection